[package]
name = "tx-pigeon"
version = "0.1.0"
edition = "2024"
default-run = "tx-pigeon"

[dependencies]
anyhow = "1.0.98"
arti-client = { version = "0.30", features = ["onion-service-client"] }
bitcoin = { version = "0.32.5", features = ["serde"] }
clap = { version = "4.5.38", features = ["derive"] }
data-encoding = "2.9.0"
futures = "0.3.31"
hex = "0.4"
libp2p = { version = "0.54.1", features = [
  "full",
  "autonat",
  "cbor",
  "dcutr",
  "dns",
  "ecdsa",
  "ed25519",
  "floodsub",
  "gossipsub",
  "identify",
  "json",
  "kad",
  "macros",
  "mdns",
  "memory-connection-limits",
  "metrics",
  "noise",
  "ping",
  "plaintext",
  "pnet",
  "quic",
  "relay",
  "rendezvous",
  "request-response",
  "rsa",
  "secp256k1",
  "serde",
  "tcp",
  "tls",
  "tokio",
  "uds",
  "upnp",
  "wasm-bindgen",
  "websocket",
  "webtransport-websys",
  "yamux",
] }
rand = "0.9.1"
reqwest = { version = "0.12.22", default-features = false, features = ["rustls-tls", "json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.10.8"
tokio = { version = "1", features = ["full"] }
tor-rtcompat = { version = "0.30", features = ["tokio"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
